# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  # Job 1: Build and test on multiple platforms
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get latest CMake
      uses: lukka/get-cmake@latest
      
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        # This specifies the location of vcpkg, where it is going to be restored and built as part of the workflow.
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        # The git commit of vcpkg when I initially cloned it and built the manifest
        vcpkgGitCommitId: '903956eff7cb94774a9e805ff573c000afc43e3e'
        vcpkgJsonGlob: '**/vcpkg.json'
        
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
              
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
      
    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.build_type == 'Release'
      with:
        name: binaries-${{ matrix.os }}
        path: |
          build/bin/*
          build/*.exe
        retention-days: 30
